import Express from "express";
import controller from "./controller";
import auth from "../../../../helper/auth";

export default Express.Router()

  .post("/signUp", controller.signup)
  .post("/login", controller.login)
  .post("/socialLogin", controller.socialLogin)
  .post("/brandSocialLogin", controller.brandSocialLogin)
  .get("/categories", controller.categories)
  .post("/forgot", controller.forgot)
  .get("/verify/:_id/:otp", controller.verify)
  .post("/resetPassword", controller.resetPassword)
  .post("/getColors", controller.getColors)


  .use(auth.verifyToken)
  .get("/profile", controller.profile)
  .put("/edit", controller.edit)
  .put("/changedPass", controller.changedPass)
  .post("/sendQuery", controller.sendQuery)
  .get("/configList", controller.configList)
  .post("/addCategory", controller.addCategory)
  .post("/createOutfit", controller.createOutfit)
  .put("/updateOutfit", controller.updateOutfit)
  .delete("/deleteOutfit", controller.deleteOutfit)
  .get("/home", controller.home)
  .get("/favourite/:_id", controller.favourite)
  .get("/favouriteList", controller.favouriteList)
  .post("/explore", controller.explore)
  .get("/outfitList", controller.outfitList)
  .put("/likeOutfits", controller.likeOutfits)
  .put("/wardrobe/:_id", controller.wardrobe)
  .get("/wardrobeList", controller.wardrobeList)
  .get('/viewOutfit', controller.viewOutfit)
  .post('/uploadFile', controller.uploadFile)
  .post('/createCollection', controller.createCollection)
  .delete('/removeCollection/:_id', controller.removeCollection)
  .get('/listCollections', controller.listCollections)
  .post('/addOutfitToCollection', controller.addOutfitToCollection)
  .delete('/removeOutfitToCollection', controller.removeOutfitToCollection)
  .put('/publicOutfit', controller.publicOutfit)
  .post('/suggestions', controller.suggestions)
  .get('/notificationList', controller.notificationList)
  .put('/updateToken', controller.updateToken)
  .delete('/deleteProfile', controller.deleteProfile)
  .get('/logout', controller.logout)

